
// &#9472;&#9472; Shared &#9472;&#9472;
const T=`<div class="fb"><button class="tb"><svg><use href="#ic-up"/></svg></button><button class="tb"><svg><use href="#ic-dn"/></svg></button></div>`;
const FP=`<p class="fp"><a href="#">Privacy Statement</a></p>`;

document.querySelectorAll('.tab').forEach(t=>t.addEventListener('click',()=>{
  document.querySelectorAll('.tab').forEach(x=>x.classList.remove('active'));
  document.querySelectorAll('.panel').forEach(x=>x.classList.remove('active'));
  t.classList.add('active');
  document.getElementById('p'+t.dataset.t).classList.add('active');
}));

function add(id,h){const c=document.getElementById(id),d=document.createElement('div');d.innerHTML=h;while(d.firstChild)c.appendChild(d.firstChild);c.scrollTop=c.scrollHeight}
function bot(t){return`<div class="m mb">${t}${T}</div>`}
function usr(t){return`<div class="m mu">${t}</div>`}

const W=`<div class="m mb">Hi. I'm an AI agent, I can help you compare plans and features, start a free trial, answer support questions or connect you with a Microsoft Sales Representative. You can also request a sales call <a href="#">here</a> or call us at (800) 642-7676 M-F 6 AM to 6 PM PT.<br><br>What can I do for you?<div class="tr-note">To learn more about this AI web feature, read the <a href="#">Transparency FAQ (PDF)</a> &#8599;</div>${T}</div><span class="ts">an hour ago</span>`;

const WA=`<div class="m mb">Hi. I'm an AI agent, I can help you compare plans and features, start a free trial, answer support questions or connect you with a Microsoft Sales Representative. You can also request a sales call <a href="#">here</a> or call us at (800) 642-7676 M-F 6 AM to 6 PM PT. What can I do for you?<div class="tr-note">To learn more about this AI web feature, read the <a href="#">Transparency FAQ (PDF)</a> &#8599;</div><div id="aA-cs" style="margin-top:6px;padding-top:4px;border-top:1px solid #eee;font-size:11px;color:#999;line-height:1.35">We may save conversations to improve your experience. If you sign in or share your email, this conversation may be connected to your profile. <a href="#" style="color:#0078d4;text-decoration:none" onclick="window._aOptOut=true;document.getElementById('aA-cs').innerHTML='<span style=\\'color:#a4262c;font-weight:600\\'>&#10003; Opted out &#8212; this conversation will not be saved.</span>';return false">[Opt out]</a></div><div style="margin-top:5px;font-size:11px"><a href="#" class="sp-return-link" onclick="window._aReturn=true;if(window._jumpa)window._jumpa(8,9);return false"><svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M15 3h4a2 2 0 012 2v14a2 2 0 01-2 2h-4"/><polyline points="10 17 15 12 10 7"/><line x1="15" y1="12" x2="3" y2="12"/></svg>Returning? Pick up where you left off</a></div>${T}</div><span class="ts">an hour ago</span>`;
document.getElementById('cA').innerHTML=WA;

const WB=`<div class="m mb">Hi. I'm an AI agent, I can help you compare plans and features, start a free trial, answer support questions or connect you with a Microsoft Sales Representative. You can also request a sales call <a href="#">here</a> or call us at (800) 642-7676 M-F 6 AM to 6 PM PT. What can I do for you?<div class="tr-note">To learn more about this AI web feature, read the <a href="#">Transparency FAQ (PDF)</a> &#8599;</div><div id="aB-cs" style="margin-top:8px;padding-top:6px;border-top:1px solid #eee;font-size:11px;color:#666;line-height:1.4">We can save this conversation to improve your experience. If you sign in or share your email, it may be connected to your profile.<div style="display:flex;gap:8px;margin-top:6px;flex-wrap:wrap"><button onclick="document.getElementById('aB-cs').innerHTML='<div style=\\'display:flex;gap:8px;align-items:center\\'><span style=\\'color:#6b3fa0;font-weight:700\\'>&#9745;</span><span style=\\'font-size:11px;color:#6b3fa0;font-weight:600\\'>Saving enabled. You can connect your email anytime.</span></div>';window._bOptIn=true;return false" style="font-size:11px;padding:4px 10px;border-radius:5px;cursor:pointer;font-weight:600;border:1px solid #8661c5;background:#8661c5;color:#fff;font-family:inherit">Yes, save and personalize</button><button onclick="window._bOptIn=false;document.getElementById('aB-cs').innerHTML='<span style=\\'color:#888;font-size:11px\\'>No data will be saved from this session.</span>';return false" style="font-size:11px;padding:4px 10px;border-radius:5px;cursor:pointer;font-weight:600;border:1px solid #ccc;background:#fff;color:#555;font-family:inherit">No, continue without saving</button></div></div>${T}</div><span class="ts">an hour ago</span>`;
document.getElementById('cB').innerHTML=WB;

const WC=`<div class="m mb">Hi. I'm an AI agent, I can help you compare plans and features, start a free trial, answer support questions or connect you with a Microsoft Sales Representative. You can also request a sales call <a href="#">here</a> or call us at (800) 642-7676 M-F 6 AM to 6 PM PT. What can I do for you?<div class="tr-note">To learn more about this AI web feature, read the <a href="#">Transparency FAQ (PDF)</a> &#8599;</div><div id="aC-cs" style="margin-top:6px;padding-top:4px;border-top:1px solid #eee;font-size:11px;color:#999;line-height:1.35">We may save conversations to improve your experience. If you sign in or share your email, this conversation may be connected to your profile. <a href="#" style="color:#2B8C96;text-decoration:none" onclick="window._cOptOut=true;document.getElementById('aC-cs').innerHTML='<span style=\\'color:#a4262c;font-weight:600\\'>&#10003; Opted out &#8212; this conversation will not be saved.</span>';return false">[Opt out]</a></div><div style="margin-top:5px;font-size:11px"><a href="#" class="sp-return-link" onclick="window._cReturn=true;if(window._jumpc)window._jumpc(8,9);return false"><svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M15 3h4a2 2 0 012 2v14a2 2 0 01-2 2h-4"/><polyline points="10 17 15 12 10 7"/><line x1="15" y1="12" x2="3" y2="12"/></svg>Returning? Pick up where you left off</a></div>${T}</div><span class="ts">an hour ago</span>`;
document.getElementById('cC').innerHTML=WC;
document.getElementById('cD').innerHTML=W;

// === Email capture block (stacked) ===
function emailBlock(label,sub){
  return `<div class="ec">
    <div class="ec-t">${label}</div>
    <div class="ec-sub">${sub}</div>
    <input type="email" placeholder="your.email@company.com">
    <button class="ec-btn" onclick="this.closest('.ec').innerHTML='<div style=\\'padding:12px;text-align:center\\'><div style=\\'color:#3F6FAE;font-weight:600;font-size:13px\\'>&#10003; Summary sent.</div></div>'">Send</button>
    <button class="ec-skip" onclick="this.closest('.ec').innerHTML='<div style=\\'padding:8px;font-size:12px;color:#888\\'>Dismissed.</div>'">Skip</button>
    ${FP}
  </div>`;
}

// === OPTION A: Notice + Opt-Out -- Preferred Consent Model ===
window._aOptOut=false;window._aEmail=true;window._aReturn=false;
const sA=[null,
  // Step 2: Customer asks about plans
  ()=>{add('cA',usr("Hi, can you help me understand what Microsoft 365 Business plans offer for a small team?"));add('cA','<span class="tsr">just now</span>')},
  // Step 3: Agent responds with plan comparison
  ()=>{add('cA',bot("Microsoft 365 Business plans come in three tiers:<br><br><strong>Business Basic</strong><br>&#10003; Web &amp; mobile versions of Word, Excel, PowerPoint<br>&#10003; 1 TB cloud storage per user<br>&#10003; Microsoft Teams for chat &amp; meetings<br><br><strong>Business Standard</strong><br>&#10003; Everything in Basic, plus full desktop apps<br>&#10003; Webinar hosting &amp; attendee registration<br>&#10003; Microsoft Loop for collaborative workspaces<br><br><strong>Business Premium</strong><br>&#10003; Everything in Standard, plus advanced security<br>&#10003; Intune device management<br>&#10003; Conditional access &amp; data loss prevention<br><br>What matters most to your team &#8212; collaboration features, desktop apps, or security?"));add('cA','<span class="ts">just now</span>')},
  // Step 4: Customer asks about security, agent responds
  ()=>{add('cA',usr("Security is a big concern &#8212; we handle customer data. What does Premium offer there?"));add('cA','<span class="tsr">just now</span>');
    setTimeout(()=>{add('cA',bot("Business Premium includes several layers of protection:<br><br>&#10003; <strong>Microsoft Defender for Business</strong> &#8212; endpoint detection &amp; response<br>&#10003; <strong>Azure Information Protection</strong> &#8212; classify &amp; protect sensitive docs<br>&#10003; <strong>Intune</strong> &#8212; manage what apps &amp; data are on employee devices<br>&#10003; <strong>Conditional Access</strong> &#8212; control who can access what, from where<br>&#10003; <strong>DLP policies</strong> &#8212; prevent accidental sharing of sensitive info<br><br>These features can help with compliance frameworks like HIPAA, SOC 2, and PCI-DSS."));add('cA','<span class="ts">just now</span>')},300)},
  // Step 5: Agent nudge (silently skipped if opted out)
  ()=>{if(window._aOptOut){window._aEmail=false;setTimeout(()=>document.getElementById('a-n').click(),50);return}add('cA',`<div class="nudge"><div class="nt">&#128231; Keep this conversation for later?</div><p>I can connect this chat to your email so you can pick up where you left off next time &#8212; and I&#39;ll send you a summary when we&#39;re done.</p><div class="nb"><button class="bp" onclick="window._aEmail=true;this.closest('.nudge').innerHTML='<div style=\\'font-size:12px;color:#888\\'>&#8594; Yes, connect my email</div>'">Yes, connect my email</button><button onclick="window._aEmail=false;this.closest('.nudge').innerHTML='<div style=\\'font-size:12px;color:#888\\'>&#8594; Not now</div>'">Not now</button></div></div>`);window._aEmail=true},
  // Step 6: Email capture (silently skipped if declined or opted out)
  ()=>{if(window._aEmail===false){setTimeout(()=>document.getElementById('a-n').click(),50);return}add('cA',`<div class="ec"><div class="ec-t">Enter your email to stay connected.</div><div class="ec-sub">You&#39;ll get a summary when we&#39;re done, and you can return to this conversation anytime.</div><input type="email" placeholder="your.email@company.com"><button class="ec-btn" onclick="this.closest('.ec').innerHTML='<div style=\\'padding:12px;text-align:center\\'><div style=\\'color:#3F6FAE;font-weight:600;font-size:13px\\'>&#10003; Connected.</div></div>'">Connect</button><button class="ec-skip" onclick="this.closest('.ec').innerHTML='<div style=\\'padding:8px;font-size:12px;color:#888\\'>Dismissed.</div>'">Skip</button>${FP}</div>`)},
  // Step 7: Confirmation + conversation continues
  ()=>{if(window._aEmail===false){add('cA',bot("No problem! Let&#39;s keep going. Anything else about those security features? Were you thinking about a specific compliance framework?"));add('cA','<span class="ts">just now</span>');return}
    add('cA','<div style="padding:8px 12px;background:#dee8f5;border:1px solid #c8e6c0;border-radius:6px;font-size:12px;color:#3F6FAE;font-weight:600;text-align:center">&#10003; Connected &#8212; I&#39;ll email you a summary when we wrap up.</div>');
    const sv=document.getElementById('aA-sv');if(sv){sv.classList.add('visible');sv.innerHTML='&#10003; <span style="color:#3F6FAE;font-weight:500">Connected to your email</span>'}
    setTimeout(()=>{add('cA',bot("Great &#8212; you&#39;re all set. Now, anything else about those security features? Were you thinking about a specific compliance framework?"));add('cA','<span class="ts">just now</span>')},400)},
  // Step 8: Customer asks follow-up -- conversation continues after email capture
  ()=>{add('cA',usr("Yes &#8212; what&#39;s the per-user pricing for Business Premium?"));add('cA','<span class="tsr">just now</span>');
    setTimeout(()=>{add('cA',bot("Business Premium is <strong>$22.00 per user/month</strong> with an annual commitment.<br><br>For comparison:<br>&#8226; Business Basic: $6.00/user/month<br>&#8226; Business Standard: $12.50/user/month<br>&#8226; Business Premium: $22.00/user/month<br><br>For a small team of, say, 10 users, that&#39;s $220/month &#8212; and it includes all the security features plus the full desktop app suite.<br><br><a href='#'>&#8594; Start a free trial</a>&nbsp;&nbsp;|&nbsp;&nbsp;<a href='#'>&#8594; Compare all plans</a>"));add('cA','<span class="ts">just now</span>')},300)},
  // === SESSION 2: RETURNING USER ===
  // Step 9: Fresh welcome -- customer returns on a new session
  ()=>{const c=document.getElementById('cA');c.innerHTML='';window._aReturn=false;
    const sv=document.getElementById('aA-sv');if(sv){sv.classList.remove('visible');sv.innerHTML=''}
    add('cA',`<div style="background:linear-gradient(135deg,#e8f4fd,#f0f7ff);border:1px solid #c0d8f0;border-radius:8px;padding:12px 16px;text-align:center;margin-bottom:8px"><div style="font-size:11px;text-transform:uppercase;letter-spacing:1px;color:#0078d4;font-weight:700">&#128260; Session 2 &#8212; New Session</div><div style="font-size:12px;color:#888;margin-top:2px">Customer returns. Click &#34;Returning?&#34; to see returning flow, or Next for a fresh conversation.</div></div>`);add('cA',WA);c.scrollTop=0},
  // Step 10: Conditional -- if Returning? clicked: email lookup. If not: fresh conversation.
  ()=>{if(!window._aReturn){add('cA',usr("I&#39;m looking at Microsoft 365 for a nonprofit. Are there discounted plans?"));add('cA','<span class="tsr">just now</span>');setTimeout(()=>{add('cA',bot("Yes! Microsoft offers significant discounts for eligible nonprofits:<br><br><strong>Microsoft 365 Business Basic</strong> &#8212; Free (up to 300 users)<br><strong>Microsoft 365 Business Premium</strong> &#8212; $5.50/user/month (75% off)<br><br>You&#39;ll need to verify nonprofit status through <a href=\'#\'>Microsoft Nonprofits</a>. The process usually takes 2&#8211;10 business days."));add('cA','<span class="ts">just now</span>')},300);return}
    add('cA',`<div class="ec-lookup" style="margin-top:6px"><div class="ec-lk-head"><div class="ec-lk-icon">&#128278;</div><div class="ec-lk-title">Welcome back</div><div class="ec-lk-sub">Enter the email from your previous session and we&#39;ll reconnect you.</div></div><div class="ec-lk-body"><input type="email" placeholder="your.email@company.com" value="user@company.com" disabled><button class="ec-lk-btn" disabled style="opacity:.7">Look up my conversation</button></div></div>`);setTimeout(()=>{const el=document.querySelector('#cA .ec-lookup');if(el){el.scrollIntoView({behavior:'smooth',block:'start'});setTimeout(()=>{const f=document.createElement('div');f.className='ec-lk-found';f.innerHTML='<div class="ec-lk-check">&#10003;</div><div class="ec-lk-found-text">Previous conversation found &#8212; ready to continue</div>';el.appendChild(f)},400)}},150)},
  // Step 11: Conditional -- if Returning?: session card. If not: continue fresh conversation.
  ()=>{if(!window._aReturn){add('cA',usr("That&#39;s great! How do we get started with the verification?"));add('cA','<span class="tsr">just now</span>');setTimeout(()=>{add('cA',bot("Here&#39;s how to get verified:<br><br>1. Go to <a href=\'#\'>nonprofit.microsoft.com</a><br>2. Create or sign in with your org account<br>3. Submit your registration number<br>4. Microsoft validates with TechSoup or local partner<br><br>Once approved, you can assign licenses from the Microsoft 365 admin center.<br><br><a href=\'#\'>&#8594; Start nonprofit registration</a>"));add('cA','<span class="ts">just now</span>')},300);return}
    add('cA',`<div class="rv" style="margin-top:6px"><div class="rv-head"><div class="rv-head-t">Continue where you left off?</div><div class="rv-head-sub">We found your previous conversation</div></div><div class="rv-body"><div class="rv-topic"><div class="ri">&#128172;</div><div class="rv-topic-info"><div class="rv-topic-title">Microsoft 365 Business plans &#8212; security &amp; pricing</div><div class="rv-topic-meta"><span>&#128197; Mar 28</span><span>&#183;</span><span>Defender, Intune, DLP, Pricing</span></div></div></div><div class="rv-acts"><button class="bp">Continue conversation</button><button>Start new</button></div></div></div>`);setTimeout(()=>{const rv=document.querySelector('#cA .rv');if(rv)rv.scrollIntoView({behavior:'smooth',block:'start'})},100);
    setTimeout(()=>add('cA',bot("Welcome back! Last time we discussed Business Premium security features &#8212; Defender, Intune, Conditional Access, DLP &#8212; and pricing at $22/user/month for a 10-person team.<br><br>Would you like to continue from there, or do you have a new question?")),300)}
];

//  OPTION B: Notice + Opt-In  Explicit Consent Model 
window._bOptIn=true;window._bEmail=true;window._bReturn=false;
const sB=[null,
  // Step 2: Customer asks about home plans
  ()=>{add('cB',usr("What features come with Microsoft 365 for home use?"));add('cB','<span class="tsr">just now</span>');
    setTimeout(()=>{add('cB',bot("For home use, there are two options:<br><br><strong>Microsoft 365 Personal</strong><br> Full desktop apps  Word, Excel, PowerPoint, Outlook<br> 1 TB OneDrive storage<br> Microsoft Editor (AI writing assistant)<br> Clipchamp video editor<br><br><strong>Microsoft 365 Family</strong><br> Everything in Personal, shared with up to 6 people<br> 6 TB total OneDrive (1 TB per person)<br> Family Safety  screen time, location sharing, content filters<br><br>Are you looking for just yourself or for family members too?"));add('cB','<span class="ts">just now</span>')},300)},
  // Step 3: Customer continues
  ()=>{add('cB',usr("Family sounds good. Can everyone install the desktop apps?"));add('cB','<span class="tsr">just now</span>');
    setTimeout(()=>{add('cB',bot("Yes  each of the 6 family members gets:<br><br> Desktop apps on up to 5 devices each (PC, Mac, tablet, phone)<br> Their own 1 TB OneDrive  fully private<br> Their own Outlook mailbox<br> Access to Microsoft Editor and Clipchamp<br><br>The Family plan is designed so each person has their own separate workspace."));add('cB','<span class="ts">just now</span>')},300)},
  // Step 4: Agent nudge (skipped if not opted in)
  ()=>{if(window._bOptIn===false){add('cB',`<div style="background:#e8eaf6;border:1px solid #ffe082;border-radius:6px;padding:8px 12px;font-size:11px;color:#8a6914;text-align:center">Customer did not opt in &mdash; no nudge or email capture. Chat continues normally.</div>`);window._bEmail=false;return}add('cB',`<div class="nudge"><div class="nt">&#9993; Add your email?</div><p>Since you opted in to save, I can also connect your email &mdash; that way I'll send you a summary and you can pick up where you left off next time. This is optional.</p><div class="nb"><button class="bp" onclick="window._bEmail=true;this.closest('.nudge').innerHTML='<div style=\\'font-size:12px;color:#888\\'>&#8594; Yes, connect my email</div>'">Yes, connect my email</button><button onclick="window._bEmail=false;this.closest('.nudge').innerHTML='<div style=\\'font-size:12px;color:#888\\'>&#8594; No thanks, just save</div>'">No thanks, just save</button></div></div>`);window._bEmail=true},
  // Step 5: Email capture (skipped if declined)
  ()=>{if(window._bEmail===false){add('cB',`<div style="background:#e8eaf6;border:1px solid #ffe082;border-radius:6px;padding:8px 12px;font-size:11px;color:#8a6914;text-align:center">Customer chose &ldquo;No thanks, just save&rdquo; &mdash; no email capture shown. Conversation saved without email.</div>`);return}add('cB',`<div class="ec"><div class="ec-t">Enter your email to stay connected.</div><div class="ec-sub">You'll get a summary when we're done, and you can return to this conversation anytime.</div><input type="email" placeholder="your.email@company.com"><button class="ec-btn" onclick="this.closest('.ec').innerHTML='<div style=\\'padding:12px;text-align:center\\'><div style=\\'color:#3F6FAE;font-weight:600;font-size:13px\\'> Connected.</div></div>'">Connect</button><button class="ec-skip" onclick="this.closest('.ec').innerHTML='<div style=\\'padding:8px;font-size:12px;color:#888\\'>Dismissed.</div>'">Skip</button>${FP}</div>`)},
  // Step 6: Confirmation + chat CONTINUES
  ()=>{if(window._bEmail===false){add('cB',bot("No problem! Your conversation is saved. Would you like to compare the Family plan pricing or learn about any specific features?"));add('cB','<span class="ts">just now</span>');return}
    add('cB',`<div style="padding:8px 12px;background:#dee8f5;border:1px solid #c8e6c0;border-radius:6px;font-size:12px;color:#3F6FAE;font-weight:600;text-align:center"> Connected  I'll email you a summary when we wrap up.</div>`);
    setTimeout(()=>{add('cB',bot("You're all set. Now, would you like to compare the Family plan pricing or learn about any specific features?"));add('cB','<span class="ts">just now</span>')},400)},
  // Step 7: Customer asks follow-up  proves chat continues after email
  ()=>{add('cB',usr("What's the pricing difference between Personal and Family?"));add('cB','<span class="tsr">just now</span>');
    setTimeout(()=>{add('cB',bot("Here's a quick comparison:<br><br><strong>Microsoft 365 Personal:</strong> $9.99/month or $99.99/year<br> 1 person, 1 TB OneDrive, all desktop apps<br><br><strong>Microsoft 365 Family:</strong> $12.99/month or $129.99/year<br> Up to 6 people, 6 TB total OneDrive<br><br>Family is just $3 more per month and covers the whole household.<br><br><a href='#'> Start a free trial</a>&nbsp;&nbsp;|&nbsp;&nbsp;<a href='#'> Compare all plans</a>"));add('cB','<span class="ts">just now</span>')},300)},
  //  VARIANT: DECLINED PATH 
  // Step 8: Reset  show what happens when customer clicks "No, continue without saving"
  ()=>{const c=document.getElementById('cB');c.innerHTML='';
    add('cB',`<div style="background:linear-gradient(135deg,#f0ebf8,#f8f5ff);border:1px solid #d4c5e9;border-radius:8px;padding:12px 16px;text-align:center;margin-bottom:8px"><div style="font-size:11px;text-transform:uppercase;letter-spacing:1px;color:#8661c5;font-weight:700"> Variant: Declined Path</div><div style="font-size:12px;color:#888;margin-top:2px">Customer clicked &ldquo;No, continue without saving&rdquo; in the welcome  what changes?</div></div>`);
    add('cB',`<div class="m mb">Hi. I'm an AI agent, I can help you compare plans and features, start a free trial, answer support questions or connect you with a Microsoft Sales Representative. You can also request a sales call <a href="#">here</a> or call us at (800) 642-7676 M-F 6 AM to 6 PM PT.<br><br>What can I do for you?<div class="tr-note">To learn more about this AI web feature, read the <a href="#">Transparency FAQ (PDF)</a> &#8599;</div><div style="margin-top:10px;padding-top:8px;border-top:1px solid #eee;font-size:11px;color:#888;line-height:1.5">No data will be saved from this session.</div>${T}</div><span class="ts">an hour ago</span>`);c.scrollTop=0},
  // Step 9: Same conversation  no nudge
  ()=>{add('cB',usr("What features come with Microsoft 365 for home use?"));add('cB','<span class="tsr">just now</span>');
    setTimeout(()=>{add('cB',bot("For home use, there are two options:<br><br><strong>Microsoft 365 Personal</strong><br> Full desktop apps  Word, Excel, PowerPoint, Outlook<br> 1 TB OneDrive storage<br><br><strong>Microsoft 365 Family</strong><br> Everything in Personal, shared with up to 6 people<br> 6 TB total OneDrive<br><br>Are you looking for yourself or for your family?"));add('cB','<span class="ts">just now</span>')},300)},
  // Step 10: Where the email nudge WOULD have been  skipped
  ()=>{add('cB',usr("Family plan  can I share it with my kids?"));add('cB','<span class="tsr">just now</span>');
    setTimeout(()=>{add('cB',bot("Absolutely. Microsoft 365 Family supports up to 6 people. Each family member gets:<br><br> Their own account and 1 TB OneDrive<br> Desktop apps on up to 5 of their own devices<br> Family Safety features  screen time limits, content filters, and location sharing<br><br>It's designed for families with shared and private spaces."));
      setTimeout(()=>add('cB',`<div style="background:#e8eaf6;border:1px solid #ffe082;border-radius:6px;padding:8px 12px;font-size:11px;color:#8a6914;text-align:center;margin-top:6px"> No email nudge shown  customer declined saving. Conversation continues normally.</div>`),400)},300)},
  // Step 11: Customer explicitly asks for summary
  ()=>{add('cB',usr("This is really helpful. Can you email me a comparison of Personal vs Family?"));add('cB','<span class="tsr">just now</span>');
    setTimeout(()=>{add('cB',bot("Of course  I'd be happy to send you a comparison."));
      setTimeout(()=>add('cB',`<div class="ec"><div class="ec-t"> Where should I send the comparison?</div><div class="ec-sub">Includes the Personal vs Family feature breakdown and pricing.</div><input type="email" placeholder="your.email@company.com"><button class="ec-btn" onclick="this.closest('.ec').innerHTML='<div style=\\'padding:12px;text-align:center\\'><div style=\\'color:#3F6FAE;font-weight:600;font-size:13px\\'> Comparison sent.</div></div>'">Send</button><button class="ec-skip" onclick="this.closest('.ec').innerHTML='<div style=\\'padding:8px;font-size:12px;color:#888\\'>Dismissed.</div>'">Skip</button>${FP}</div>`),300)},300)},
  // Step 12: Annotation
  ()=>{add('cB',bot(" Comparison sent! If you'd like to continue this conversation next time, just enter your email when you return."));
    add('cB',`<div style="background:#e8eaf6;border:1px solid #ffe082;border-radius:6px;padding:8px 12px;font-size:11px;color:#8a6914;text-align:center;margin-top:6px"> Email captured via explicit customer request  not an agent nudge. Declined preference respected.</div>`)},
  //  SESSION 2: RETURNING USER 
  // Step 13: Returning user -- fresh session welcome with Returning? link
  ()=>{const c=document.getElementById('cB');c.innerHTML='';window._bReturn=false;
    add('cB',`<div style="background:linear-gradient(135deg,#f0ebf8,#f8f5ff);border:1px solid #d4c5e9;border-radius:8px;padding:12px 16px;text-align:center;margin-bottom:8px"><div style="font-size:11px;text-transform:uppercase;letter-spacing:1px;color:#8661c5;font-weight:700">&#128260; Session 2 &#8212; New Session</div><div style="font-size:12px;color:#888;margin-top:2px">Customer returns. Click &#34;Returning?&#34; to see returning flow, or Next for a fresh conversation.</div></div>`);
    const wb=`<div class="m mb">${W.match(/<div class="m mb">([\s\S]*?)<\/div><span/)[1]}<div style="margin-top:5px;font-size:11px"><a href="#" class="sp-return-link" onclick="window._bReturn=true;if(window._jumpb)window._jumpb(12,13);return false"><svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M15 3h4a2 2 0 012 2v14a2 2 0 01-2 2h-4"/><polyline points="10 17 15 12 10 7"/><line x1="15" y1="12" x2="3" y2="12"/></svg>Returning? Pick up where you left off</a></div>${T}</div><span class="ts">an hour ago</span>`;
    add('cB',wb);c.scrollTop=0},
  // Step 14: Conditional -- if Returning?: email lookup. If not: fresh conversation.
  ()=>{if(!window._bReturn){add('cB',usr("What&#39;s the difference between Microsoft 365 and Office 2024?"));add('cB','<span class="tsr">just now</span>');setTimeout(()=>{add('cB',bot("Great question! The key differences:<br><br><strong>Microsoft 365</strong> (subscription)<br>&#10003; Always up to date with latest features<br>&#10003; 1 TB OneDrive cloud storage<br>&#10003; Works across all your devices<br>&#10003; Microsoft Teams, Editor, Clipchamp included<br><br><strong>Office 2024</strong> (one-time purchase)<br>&#10003; Classic desktop apps only<br>&#10003; No cloud storage or updates<br>&#10003; Single PC or Mac license<br><br>For a family, Microsoft 365 Family is usually the better value."));add('cB','<span class="ts">just now</span>')},300);return}
    add('cB',`<div class="ec" style="margin-top:4px"><div class="ec-t">Enter the email from your previous session.</div><div class="ec-sub">This will load your conversation summary.</div><input type="email" placeholder="your.email@company.com" value="user@family.com" disabled><button class="ec-btn" disabled style="opacity:.7">Continue</button></div>`);setTimeout(()=>add('cB',`<div style="padding:10px;text-align:center;color:#3F6FAE;font-weight:600;font-size:13px">&#10003; Summary found.</div>`),400)},
  // Step 15: Conditional -- if Returning?: session card. If not: continue fresh.
  ()=>{if(!window._bReturn){add('cB',usr("Can I switch from Office 2024 to Microsoft 365 later?"));add('cB','<span class="tsr">just now</span>');setTimeout(()=>{add('cB',bot("Absolutely! You can subscribe to Microsoft 365 anytime &#8212; your Office 2024 license stays valid, but Microsoft 365 apps take priority once installed.<br><br>Many people start with Office 2024 and switch when they need cloud features or multi-device access.<br><br><a href=\'#\'>&#8594; Compare plans side by side</a>"));add('cB','<span class="ts">just now</span>')},300);return}
    add('cB',`<div class="rv" style="margin-top:4px"><div class="rv-t">Continue a previous conversation?</div><div class="rv-topic"><span class="ri">&#128172;</span><div><strong>Microsoft 365 Family &#8212; features &amp; pricing</strong><br><span style="font-size:11px;color:#888">Mar 28 &#183; Personal vs Family, desktop apps, OneDrive, pricing</span></div></div><div class="rv-acts"><button class="bp">Continue</button><button>Start new</button></div></div>`);
    setTimeout(()=>add('cB',bot("Previous summary: Microsoft 365 Family &#8212; up to 6 people, desktop apps on 5 devices each, 1 TB OneDrive per person. Family plan: $12.99/month. Personal: $9.99/month.")),300)}
];


// === OPTION C: Notice + Opt-Out with End-of-Chat Summary ===
window._cOptOut=false;window._cEmail=true;window._cReturn=false;
const sC=[null,
  // Step 2: Customer asks about freelancer plans
  ()=>{add('cC',usr("What&#39;s included with Microsoft 365 for a freelancer?"));add('cC','<span class="tsr">just now</span>')},
  // Step 3: Agent responds with M365 Personal features
  ()=>{add('cC',bot("Microsoft 365 Personal is a great fit for freelancers:<br><br>&#10003; <strong>Desktop apps</strong> &#8212; Word, Excel, PowerPoint, Outlook<br>&#10003; <strong>1 TB OneDrive</strong> &#8212; share files with clients securely<br>&#10003; <strong>Microsoft Editor</strong> &#8212; AI-powered writing &amp; grammar<br>&#10003; <strong>Clipchamp</strong> &#8212; create &amp; edit videos<br>&#10003; <strong>Outlook calendar</strong> &#8212; schedule client meetings<br>&#10003; <strong>Microsoft Designer</strong> &#8212; create social media graphics<br><br>Would you like to know about any specific feature?"));add('cC','<span class="ts">just now</span>')},
  // Step 4: Customer asks about free trial
  ()=>{add('cC',usr("Can I try it first?"));add('cC','<span class="tsr">just now</span>');
    setTimeout(()=>{add('cC',bot("Yes &#8212; there&#39;s a 1-month free trial with full access to everything, including desktop apps, 1 TB OneDrive, and all the AI features. No commitment required.<br><br><a href=\'#\'>&#8594; Start your free trial</a>"));add('cC','<span class="ts">just now</span>')},300)},
  // Step 5: Follow-up question about Clipchamp
  ()=>{add('cC',usr("What can I do with Clipchamp exactly?"));add('cC','<span class="tsr">just now</span>');
    setTimeout(()=>{add('cC',bot("<strong>Clipchamp</strong> is a video editor built into Microsoft 365:<br><br>&#10003; Trim, merge, and crop video clips<br>&#10003; Add text overlays, transitions, and music<br>&#10003; Screen recording with webcam overlay<br>&#10003; AI-powered auto-captions<br>&#10003; Export up to 1080p<br>&#10003; Social media templates (Instagram, TikTok, YouTube)<br><br>It&#39;s great for creating client presentations, social content, or training videos."));add('cC','<span class="ts">just now</span>')},300)},
  // Step 6: Customer wraps up -- agent offers summary (skipped if opted out)
  ()=>{if(window._cOptOut){add('cC',usr("Great, thanks for all the info!"));add('cC','<span class="tsr">just now</span>');setTimeout(()=>{add('cC',bot("You&#39;re welcome! Good luck with your freelancing. If you need anything else, just come back anytime.<br><br><a href=\'#\'>&#8594; Start your free trial</a>"));add('cC','<span class="ts">just now</span>')},300);return}
    add('cC',usr("Great, thanks for all the info!"));add('cC','<span class="tsr">just now</span>');
    setTimeout(()=>{add('cC',bot("Happy to help! Before you go &#8212; would you like me to put together a quick summary of what we covered? I can email it to you so you have it handy."));
      setTimeout(()=>add('cC',`<div class="qr"><button class="bp" onclick="window._cEmail=true;this.parentElement.innerHTML='<span style=\\'font-size:12px;color:#888\\'>&#8594; Yes, email me a summary</span>';setTimeout(()=>document.getElementById('c-n').click(),600)">Yes, email me a summary</button><button onclick="window._cEmail=false;this.parentElement.innerHTML='<span style=\\'font-size:12px;color:#888\\'>&#8594; No thanks, I&#39;m good</span>';setTimeout(()=>document.getElementById('c-n').click(),600)">No thanks, I&#39;m good</button></div>`),300)},300)},
  // Step 7: Email capture or skip (conditional)
  ()=>{if(window._cOptOut||!window._cEmail){add('cC',bot("No problem! Good luck with your freelancing. If you need anything else, just come back anytime. &#128075;"));add('cC','<span class="ts">just now</span>');return}
    add('cC',`<div class="sc"><div class="sh">&#128203; Conversation Summary</div><div class="sb"><ul><li><strong>Recommended:</strong> Microsoft 365 Personal ($9.99/month)</li><li><strong>Key features:</strong> Desktop apps, 1 TB OneDrive, Editor, Clipchamp, Designer</li><li><strong>Clipchamp:</strong> Video editor with AI captions and social templates</li><li><strong>Next step:</strong> Free 1-month trial available</li></ul></div></div>`);
    setTimeout(()=>add('cC',emailBlock("&#128231; Where should I send the summary?","Includes your M365 Personal overview and free trial link.")),400)},
  // Step 8: Confirmation
  ()=>{if(window._cOptOut||!window._cEmail){setTimeout(()=>document.getElementById('c-n').click(),50);return}
    add('cC',bot("Summary sent! &#128232; You can also return anytime and enter your email to continue where we left off. Have a great day!"));add('cC','<span class="ts">just now</span>')},
  // === SESSION 2: RETURNING USER ===
  // Step 9: Fresh session welcome
  ()=>{const c=document.getElementById('cC');c.innerHTML='';window._cReturn=false;
    add('cC',`<div style="background:linear-gradient(135deg,#EDF7F8,#faecd4);border:1px solid #8CC8CE;border-radius:8px;padding:12px 16px;text-align:center;margin-bottom:8px"><div style="font-size:11px;text-transform:uppercase;letter-spacing:1px;color:#2B8C96;font-weight:700">&#128260; Session 2 &#8212; New Session</div><div style="font-size:12px;color:#888;margin-top:2px">Customer returns. Click &#34;Returning?&#34; to see returning flow, or Next for a fresh conversation.</div></div>`);add('cC',WC);c.scrollTop=0},
  // Step 10: Conditional -- if Returning?: email lookup. If not: fresh conversation.
  ()=>{if(!window._cReturn){add('cC',usr("I want to set up Microsoft Designer for social media graphics. How do I start?"));add('cC','<span class="tsr">just now</span>');setTimeout(()=>{add('cC',bot("Getting started with Designer is easy:<br><br>1. Go to <a href=\'#\'>designer.microsoft.com</a><br>2. Sign in with your Microsoft 365 account<br>3. Choose a template or start from scratch<br>4. Use AI to generate images and layouts<br><br>It works in the browser and there&#39;s also a Windows app. All your designs save to OneDrive automatically."));add('cC','<span class="ts">just now</span>')},300);return}
    add('cC',`<div class="ec-lookup" style="margin-top:6px"><div class="ec-lk-head"><div class="ec-lk-icon">&#128278;</div><div class="ec-lk-title">Welcome back</div><div class="ec-lk-sub">Enter the email from your previous session and we&#39;ll reconnect you.</div></div><div class="ec-lk-body"><input type="email" placeholder="your.email@company.com" value="freelancer@email.com" disabled><button class="ec-lk-btn" disabled style="opacity:.7">Look up my conversation</button></div></div>`);setTimeout(()=>{const el=document.querySelector('#cC .ec-lookup');if(el){el.scrollIntoView({behavior:'smooth',block:'start'});setTimeout(()=>{const f=document.createElement('div');f.className='ec-lk-found';f.innerHTML='<div class="ec-lk-check">&#10003;</div><div class="ec-lk-found-text">Previous conversation found &#8212; ready to continue</div>';el.appendChild(f)},400)}},150)},
  // Step 11: Conditional -- if Returning?: session card. If not: continue fresh.
  ()=>{if(!window._cReturn){add('cC',usr("Can I use it on my phone too?"));add('cC','<span class="tsr">just now</span>');setTimeout(()=>{add('cC',bot("Yes! Microsoft Designer has mobile apps for both iOS and Android. Create and edit on the go, and everything syncs with your OneDrive.<br><br><a href=\'#\'>&#8594; Download Microsoft Designer</a>"));add('cC','<span class="ts">just now</span>')},300);return}
    add('cC',`<div class="rv" style="margin-top:6px"><div class="rv-head" style="background:linear-gradient(135deg,#2B8C96,#1E6B73)"><div class="rv-head-t">Continue where you left off?</div><div class="rv-head-sub">We found your previous conversation</div></div><div class="rv-body"><div class="rv-topic"><div class="ri">&#128172;</div><div class="rv-topic-info"><div class="rv-topic-title">Microsoft 365 Personal for freelancers</div><div class="rv-topic-meta"><span>&#128197; Yesterday</span><span>&#183;</span><span>Desktop apps, OneDrive, Clipchamp, free trial</span></div></div></div><div class="rv-acts"><button class="bp" style="background:#2B8C96!important;border-color:#2B8C96!important">Continue conversation</button><button>Start new</button></div></div></div>`);setTimeout(()=>{const rv=document.querySelector('#cC .rv');if(rv)rv.scrollIntoView({behavior:'smooth',block:'start'})},100);
    setTimeout(()=>add('cC',bot("Welcome back! Last time we explored Microsoft 365 Personal for freelancing &#8212; desktop apps, 1 TB OneDrive, Editor, Clipchamp, and Designer. You were looking at the free trial.<br><br>Want to continue from there, or do you have a new question?")),300)}
];


// === OPTION D: Always-On Passive Button ===
const sD=[null,
  // Step 2: Customer asks about Surface devices
  ()=>{add('cD',usr("I&#39;m looking at Surface laptops for my team. What are the differences between Surface Laptop and Surface Pro?"));add('cD','<span class="tsr">just now</span>');
    setTimeout(()=>{add('cD',bot("Great question. Here&#39;s how they compare:<br><br><strong>Surface Laptop</strong><br>&#10003; Traditional clamshell laptop design<br>&#10003; 13.8&#34; or 15&#34; PixelSense display<br>&#10003; Full-size keyboard with haptic trackpad<br>&#10003; Best for everyday productivity and portability<br><br><strong>Surface Pro</strong><br>&#10003; 2-in-1 tablet with detachable keyboard<br>&#10003; 13&#34; PixelSense Flow display (120Hz)<br>&#10003; Supports Surface Slim Pen 2 for inking<br>&#10003; Best for flexibility &#8212; tablet, laptop, or studio mode<br><br>Both run Windows 11 and support Copilot. Are you leaning toward traditional laptops or the versatility of a 2-in-1?"));add('cD','<span class="ts">just now</span>')},300)},
  // Step 3: Conversation continues naturally
  ()=>{add('cD',usr("Laptop format works better for us. How much is the Surface Laptop for business?"));add('cD','<span class="tsr">just now</span>');
    setTimeout(()=>{add('cD',bot("Surface Laptop for Business starts at:<br><br><strong>Surface Laptop 7 for Business</strong><br>&#8226; 13.8&#34; &#8212; from $1,399<br>&#8226; 15&#34; &#8212; from $1,699<br><br>Both come with:<br>&#10003; Snapdragon X Elite or Intel Core Ultra processors<br>&#10003; Up to 64 GB RAM, 1 TB SSD<br>&#10003; Windows 11 Pro with Copilot<br>&#10003; Enterprise-grade security (TPM 2.0, Secured-core)<br><br>Volume licensing and Surface Plus financing are also available for fleet purchases."));add('cD','<span class="ts">just now</span>')},300)},
  // Step 4: More conversation
  ()=>{add('cD',usr("Can you compare the warranty options for business orders?"));add('cD','<span class="tsr">just now</span>');
    setTimeout(()=>{add('cD',bot("For business Surface devices, you have three warranty tiers:<br><br><strong>Standard Warranty</strong> (included)<br>&#10003; 1 year hardware warranty<br>&#10003; 90 days of technical support<br><br><strong>Microsoft Complete for Business</strong><br>&#10003; Extends coverage to 3 or 4 years<br>&#10003; Accidental damage protection (2 claims)<br>&#10003; Next business day replacement<br><br><strong>Microsoft Complete for Business Plus</strong><br>&#10003; Everything above, plus on-site service<br>&#10003; Battery replacement after 50% degradation<br><br>For a team order, I&#39;d recommend Complete for Business &#8212; it covers the most common issues during a 3-year refresh cycle."));add('cD','<span class="ts">just now</span>')},300)},
  // Step 5: Bulk ordering question
  ()=>{add('cD',usr("What about bulk ordering? We need about 50 units."));add('cD','<span class="tsr">just now</span>');
    setTimeout(()=>{add('cD',bot("For a 50-unit order, I&#39;d recommend going through a <strong>Microsoft Authorized Reseller</strong> or your Microsoft account team:<br><br>&#10003; Volume pricing with discounts<br>&#10003; Custom configuration options<br>&#10003; Centralized deployment with Autopilot<br>&#10003; Surface Plus financing &#8212; spread costs over 24 or 36 months<br><br>I can connect you with a Surface specialist who handles fleet orders. Would you like that?"));add('cD','<span class="ts">just now</span>')},300)},
  // Step 6: Docking stations follow-up
  ()=>{add('cD',usr("Yes, that sounds great. Also, do they come with docking stations?"));add('cD','<span class="tsr">just now</span>');
    setTimeout(()=>{add('cD',bot("Great question! The <strong>Surface Thunderbolt 4 Dock</strong> is the recommended option:<br><br>&#10003; Dual 4K monitor support<br>&#10003; USB-C, USB-A, Ethernet, and audio ports<br>&#10003; 96W power delivery &#8212; charges the laptop while docked<br>&#10003; $299 per dock<br><br>For a fleet of 50, your reseller can bundle docks with the laptops for a package deal."));add('cD','<span class="ts">just now</span>')},300)},
  // Step 7: Another follow-up
  ()=>{add('cD',usr("What about deployment? Can we pre-configure them before handing out to employees?"));add('cD','<span class="tsr">just now</span>');
    setTimeout(()=>{add('cD',bot("Absolutely. <strong>Windows Autopilot</strong> lets you:<br><br>&#10003; Pre-register devices by serial number<br>&#10003; Auto-configure policies, apps, and settings on first boot<br>&#10003; Ship directly to employees &#8212; they sign in and everything is ready<br>&#10003; No IT touch required for imaging<br><br>Paired with Intune, you can manage all 50 devices from a single dashboard. Most resellers can register Autopilot profiles as part of the order."));add('cD','<span class="ts">just now</span>')},300)},
  // Step 8: Final question
  ()=>{add('cD',usr("That&#39;s really helpful. Can I get a formal quote for 50 Laptop 7s with docks and Complete for Business?"));add('cD','<span class="tsr">just now</span>');
    setTimeout(()=>{add('cD',bot("I can connect you with a Surface sales specialist who can prepare a formal quote. They&#39;ll include:<br><br>&#10003; 50x Surface Laptop 7 for Business (your config)<br>&#10003; 50x Surface Thunderbolt 4 Docks<br>&#10003; Microsoft Complete for Business (3-year)<br>&#10003; Volume pricing and financing options<br><br><a href='#'>&#8594; Request a quote</a>&nbsp;&nbsp;|&nbsp;&nbsp;<a href='#'>&#8594; Talk to a specialist</a>"));add('cD','<span class="ts">just now</span>')},300)},
  // === SESSION 2: RETURNING USER ===
  // Step 9: Customer returns -- same welcome with Returning? link
  ()=>{const c=document.getElementById('cD');c.innerHTML='';window._dReturn=false;
    const lnk=document.getElementById('aD-link');if(lnk){lnk.innerHTML='<svg class="sp-icon" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M19 21l-7-5-7 5V5a2 2 0 012-2h10a2 2 0 012 2z"/></svg><span class="sp-label">Save chat</span><span class="sp-tip">Save this conversation to your email and return later</span>';delete lnk.dataset.saved}
    add('cD',`<div style="background:linear-gradient(135deg,#e8f5e9,#f0faf0);border:1px solid #a5d6a7;border-radius:8px;padding:12px 16px;text-align:center;margin-bottom:8px"><div style="font-size:11px;text-transform:uppercase;letter-spacing:1px;color:#107C10;font-weight:700">&#128260; Session 2 &#8212; New Session</div><div style="font-size:12px;color:#888;margin-top:2px">Customer returns. Click &#34;Returning?&#34; to see returning flow, or Next for a fresh conversation.</div></div>`);
    const wd=`<div class="m mb">${W.match(/<div class="m mb">([\s\S]*?)<\/div><span/)[1]}<div style="margin-top:5px;font-size:11px"><a href="#" class="sp-return-link" onclick="window._dReturn=true;if(window._jumpd)window._jumpd(8,9);return false"><svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M15 3h4a2 2 0 012 2v14a2 2 0 01-2 2h-4"/><polyline points="10 17 15 12 10 7"/><line x1="15" y1="12" x2="3" y2="12"/></svg>Returning? Pick up where you left off</a></div>${T}</div><span class="ts">an hour ago</span>`;
    add('cD',wd);c.scrollTop=0},
  // Step 10: Conditional -- if Returning? clicked: email lookup. If not: fresh conversation.
  ()=>{if(!window._dReturn){add('cD',usr("Hi, I&#39;m looking at Surface Pro 10 for our remote workers. What&#39;s the starting price?"));add('cD','<span class="tsr">just now</span>');setTimeout(()=>{add('cD',bot("The <strong>Surface Pro 10 for Business</strong> starts at <strong>$1,199</strong> with:<br><br>&#10003; Intel Core Ultra processor<br>&#10003; 16 GB RAM / 256 GB SSD<br>&#10003; 13&#34; PixelSense Flow touchscreen<br>&#10003; Up to 16 hours battery life<br>&#10003; Optional 5G connectivity<br><br>For remote workers, the 5G model is popular &#8212; $1,499 starting. The Surface Pro Keyboard and Slim Pen are sold separately."));add('cD','<span class="ts">just now</span>')},300);return}
    add('cD',`<div class="ec-lookup" style="margin-top:6px"><div class="ec-lk-head"><div class="ec-lk-icon">&#128278;</div><div class="ec-lk-title">Welcome back</div><div class="ec-lk-sub">Enter the email from your previous session and we&#39;ll reconnect you.</div></div><div class="ec-lk-body"><input type="email" placeholder="your.email@company.com" value="j.chen@contoso.com" disabled><button class="ec-lk-btn" disabled style="opacity:.7">Look up my conversation</button></div></div>`);setTimeout(()=>{const el=document.querySelector('#cD .ec-lookup');if(el){el.scrollIntoView({behavior:'smooth',block:'start'});setTimeout(()=>{const f=document.createElement('div');f.className='ec-lk-found';f.innerHTML='<div class="ec-lk-check">&#10003;</div><div class="ec-lk-found-text">Previous conversation found &#8212; ready to continue</div>';el.appendChild(f)},400)}},150)},
  // Step 11: Conditional -- if Returning?: session card. If not: continue fresh.
  ()=>{if(!window._dReturn){add('cD',usr("Does it come with a keyboard or do we need to buy those separately?"));add('cD','<span class="tsr">just now</span>');setTimeout(()=>{add('cD',bot("The keyboard is sold separately for Surface Pro 10:<br><br><strong>Surface Pro Keyboard</strong> &#8212; $179<br>&#10003; Full-size, backlit keys<br>&#10003; Integrated kickstand support<br><br><strong>Surface Pro Keyboard with Slim Pen</strong> &#8212; $279<br>&#10003; Everything above + Surface Slim Pen 2<br>&#10003; Pen charges wirelessly in the keyboard<br><br>For fleet orders, your reseller can bundle keyboards at a discount."));add('cD','<span class="ts">just now</span>')},300);return}
    add('cD',`<div class="rv" style="margin-top:6px"><div class="rv-head" style="background:linear-gradient(135deg,#107C10,#0b5e0b)"><div class="rv-head-t">Continue where you left off?</div><div class="rv-head-sub">We found your previous conversation</div></div><div class="rv-body"><div class="rv-topic"><div class="ri">&#128187;</div><div class="rv-topic-info"><div class="rv-topic-title">Surface Laptop for Business &#8212; pricing, warranty &amp; fleet</div><div class="rv-topic-meta"><span>&#128197; Mar 28</span><span>&#183;</span><span>Laptop vs Pro, warranty tiers, bulk ordering</span></div></div></div><div class="rv-acts"><button class="bp" style="background:#107C10!important;border-color:#107C10!important">Continue conversation</button><button>Start new</button></div></div></div>`);setTimeout(()=>{const rv=document.querySelector('#cD .rv');if(rv)rv.scrollIntoView({behavior:'smooth',block:'start'})},100);
    setTimeout(()=>add('cD',bot("Welcome back! Last time we discussed Surface Laptop 7 for Business starting at $1,399, warranty options including Complete for Business, and a 50-unit fleet order with docking stations.<br><br>Would you like to continue from there, or do you have a new question?")),300)}
];



// === OPTION D: Save chat handler ===
window._dSave=function(){
  var lnk=document.getElementById('aD-link');
  if(!lnk||lnk.dataset.saved)return;
  lnk.dataset.saved='1';
  var c=document.getElementById('cD');
  var card=document.createElement('div');card.className='ec';card.style.marginTop='4px';
  card.innerHTML='<div class="ec-t">Save this conversation</div>'
    +'<div class="ec-sub">Enter your email to get a summary and pick up where you left off next time.</div>'
    +'<input type="email" placeholder="your.email@company.com">'
    +'<button class="ec-btn">Connect</button>';
  card.querySelector('.ec-btn').addEventListener('click',function(){
    card.innerHTML='<div style="padding:12px;text-align:center"><div style="color:#107C10;font-weight:600;font-size:13px">&#10003; Connected. Your conversation will be saved.</div></div>';
    lnk.innerHTML='<svg class="sp-icon" viewBox="0 0 24 24" fill="#107C10" stroke="#107C10" stroke-width="2"><path d="M19 21l-7-5-7 5V5a2 2 0 012-2h10a2 2 0 012 2z"/></svg><span class="sp-label" style="color:#107C10;font-weight:600">&#10003; Saved</span>';
  });
  c.appendChild(card);
  c.scrollTop=c.scrollHeight;
};

// === STEPPER ENGINE ===
function mkStep(p,steps,wHtml){
    let s=0;const n=steps.length;
  const pb=document.getElementById(p+'-p'),nb=document.getElementById(p+'-n'),lb=document.getElementById(p+'-l');
  function u(){lb.textContent=`${s+1} / ${n}`;pb.disabled=s<=0;nb.disabled=s>=n-1}
  function rst(){document.getElementById('c'+p.toUpperCase()).innerHTML=wHtml}
  nb.addEventListener('click',()=>{if(s<n-1){s++;if(steps[s])steps[s]();u()}});
  pb.addEventListener('click',()=>{if(s>0){rst();s--;for(let i=1;i<=s;i++)if(steps[i])steps[i]();u()}});
  window['_jump'+p]=function(from,to){document.getElementById('c'+p.toUpperCase()).innerHTML='';for(let i=from;i<=to;i++){s=i;if(steps[i])steps[i]()}u()};
  u();
}
mkStep('a',sA,WA);mkStep('b',sB,W);mkStep('c',sC,W);mkStep('d',sD,W);
